server:
  port: 8888
eureka:
  instance:
    lease-renewal-interval-in-seconds: 20 #租期更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 60 #租期到期时间（默认90秒）
    instance-id: ${serviceIp}:${server.port}
    ip-address: ${serviceIp}    # 使用docker部署时 指定此实例的ip
    prefer-ip-address: true    # 注册时使用ip而不是主机名
  client:
    healthcheck:
      enabled: true #开启健康检查（需要spring-boot-starter-actuator依赖）
    serviceUrl:
      defaultZone: http://35.201.196.124:1111/eureka/,http://35.220.222.101:1111/eureka/

zuul:
  routes:
    auth:
      path: /auth/**
      serviceId: auth-service
    department:
      path: /department/**
      serviceId: department-service
    employee:
      path: /employee/**
      serviceId: employee-service
    organization:
      path: /organization/**
      serviceId: organization-service

# redis (RedisProperties)
spring:
  redis:
    host: localhost # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    database: 0  # Redis数据库索引（默认为0）
    lettuce:
      pool:
        max-active: 50 #连接池最大连接数（使用负值表示没有限制）
        pool.max-wait: 3000 #连接池最大阻塞等待时间（使用负值表示没有限制）
        pool.max-idle: 20 #连接池中的最大空闲连接
        pool.min-idle: 2 #连接池中的最小空闲连接

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"