server:
  port: 8888
spring:
  application:
    name: gateway-service
  profiles:
    active: ${env}

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"