spring:
  application:
    name: gateway-service
  profiles:
    active: dev


management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"